<?php

namespace eRede\Classes;

class ReturnResponse
{
    const CODES = [
        '00',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
        '43',
        '44',
        '45',
        '46',
        '47',
        '48',
        '49',
        '50',
        '51',
        '53',
        '54',
        '55',
        '56',
        '57',
        '58',
        '59',
        '60',
        '61',
        '63',
        '64',
        '65',
        '66',
        '67',
        '68',
        '69',
        '70',
        '71',
        '72',
        '73',
        '74',
        '75',
        '76',
        '78',
        '79',
        '80',
        '82',
        '83',
        '84',
        '85',
        '86',
        '87',
        '88',
        '89',
        '97',
        '98',
        '99',
        '100',
        '101',
        '102',
        '103',
        '104',
        '105',
        '106',
        '107',
        '108',
        '109',
        '110',
        '111',
        '112',
        '113',
        '114',
        '115',
        '116',
        '117',
        '118',
        '119',
        '121',
        '122',
        '123',
        '124',
        '132',
        '133',
        '150',
        '151',
        '153',
        '154',
        '155',
        '156',
        '157',
        '158',
        '159',
        '160',
        '161',
        '167',
        '169',
        '170',
        '171',
        '172',
        '173',
        '174',
        '175',
        '176',
        '200',
        '201',
        '203',
        '202',
        '204',
        '220',
        '250',
        '251',
        '252',
        '253',
        '254',
        '255',
        '256',
        '257',
        '258',
        '259',
        '260',
        '261',
        '269',
        '351',
        '353',
        '354',
        '355',
        '357',
        '358',
        '359',
        '360',
        '362',
        '363',
        '365',
        '368',
        '369',
        '370',
        '371',
        '373',
        '374',
        '898',
        '899',
        '1002',
        '1003',
        '1018',
        '1019',
        '1020',
        '1021',
        '1023',
        '1027',
        '1030',
        '1032',
        '1034',
        '1036',
        '1038',
        '3000',
        '3001',
        '3002',
        '3003',
        '3004',
        '3005',
        '3006',
        '3007',
        '3008',
        '3009',
        '3010',
        '3011',
        '3012',
        '3013',
        '3014',
        '3015',
        '3016',
        '3017',
        '3018',
        '3019',
        '3020',
        '3025',
        '3026',
        '3027',
        '3028',
        '3029',
        '3030',
        '3031',
        '3032',
        '3033',
        '3034',
        '3035',
        '3036',
        '3052',
        '3053',
        '3054',
        '3055',
        '3056',
        '3064',
        '3065',
        '3066',
        '3067',
        '3068',
        '3069',
        '3070',
        '3076',
        '3077',
        '3078',
        '3079',
        '3081',
        '3084',
        '3085',
        '3089',
        '3090',
        '3091',
        '3092',
        '3094',
        '3095',
        '3096',
        '3097',
        '3098',
        '3099',
        '3100',
        '3101',
        '3102',
        '3103',
        '3104',
        '3105',
        '3106',
        '3107',
        '3108',
        '3109',
        '3110',
        '3111',
        '3112',
        '3113',
        '3114',
        '3115',
        '3116',
        '3117',
        '3118',
        '3119',
        '3120',
        '3121',
        '3122',
        '3123',
        '3125',
        '3128',
        '3130',
        '3131',
        '3132',
        '3133',
    ];

    const MESSAGES = [
        '00' => 'Sucesso',
        '1' => 'Parâmetro enviado com tamanho inválido',
        '2' => 'Formato do parâmetro inválido',
        '3' => 'Parâmetro obrigatório não está presente',
        '4' => 'Parâmetro enviado com tamanho inválido',
        '5' => 'Formato do parâmetro inválido',
        '6' => 'Parâmetro enviado com tamanho inválido',
        '7' => 'Formato do parâmetro inválido',
        '8' => 'Parâmetro obrigatório não está presente',
        '9' => 'Parâmetro enviado com tamanho inválido',
        '10' => 'Formato do parâmetro inválido',
        '11' => 'Formato do parâmetro inválido',
        '12' => 'Parâmetro enviado com tamanho inválido',
        '13' => 'Formato do parâmetro inválido',
        '14' => 'Parâmetro obrigatório não está presente',
        '15' => 'Parâmetro enviado com tamanho inválido',
        '16' => 'Formato do parâmetro inválido',
        '17' => 'Parâmetro enviado com tamanho inválido',
        '18' => 'Formato do parâmetro inválido',
        '19' => 'Parâmetro enviado com tamanho inválido',
        '20' => 'Formato do parâmetro inválido',
        '21' => 'Parâmetro obrigatório para Visa não está presente',
        '22' => 'Parâmetro obrigatório não está presente',
        '23' => 'Formato do parâmetro inválido',
        '24' => 'Parâmetro enviado com tamanho inválido',
        '25' => 'Formato do parâmetro inválido',
        '26' => 'Parâmetro obrigatório não está presente',
        '27' => 'Parâmetro cavv ou eci não está presente',
        '28' => 'Parâmetro enviado com tamanho inválido',
        '29' => 'Formato do parâmetro inválido',
        '30' => 'Parâmetro obrigatório não está presente',
        '31' => 'Parâmetro enviado com tamanho inválido',
        '32' => 'Formato do parâmetro inválido',
        '33' => 'Formato do parâmetro inválido',
        '34' => 'Formato do parâmetro inválido',
        '35' => 'Parâmetro obrigatório não está presente',
        '36' => 'Parâmetro enviado com tamanho inválido',
        '37' => 'Formato do parâmetro inválido',
        '38' => 'Parâmetro obrigatório não está presente',
        '39' => 'Parâmetro enviado com tamanho inválido',
        '40' => 'Formato do parâmetro inválido',
        '41' => 'Parâmetro obrigatório não está presente',
        '42' => 'Número de pedido já existente',
        '43' => 'Parâmetro enviado com tamanho inválido',
        '44' => 'Formato do parâmetro inválido',
        '45' => 'Parâmetro obrigatório não está presente',
        '46' => 'Quantidade de parcelas não corresponde com a transação autorizada',
        '47' => 'Formato do parâmetro inválido',
        '48' => 'Parâmetro enviado com tamanho inválido',
        '49' => 'O valor da transação excede o valor autorizado',
        '50' => 'Formato do parâmetro inválido',
        '51' => 'Produto ou serviço desabilitado para esse lojista. Contate a Rede',
        '53' => 'Transação não permitida para este emissor. Contate a Rede',
        '54' => 'Parâmetro não permitido para esta transação',
        '55' => 'Parâmetro enviado com tamanho inválido',
        '56' => 'Erro nos dados reportados. Tente novamente',
        '57' => 'Lojista inválido enviado no parâmetro',
        '58' => 'Não autorizado. Contate a central do cartão',
        '59' => 'Formato do parâmetro inválido',
        '60' => 'Parâmetro enviado com tamanho inválido',
        '61' => 'Formato do parâmetro inválido',
        '63' => 'Produto não habilitado',
        '64' => 'Transação não processada. Tente novamente',
        '65' => 'Chave de integração não está presente',
        '66' => 'Parâmetro enviado com tamanho inválido',
        '67' => 'Formato do parâmetro inválido',
        '68' => 'Parâmetro obrigatório não está presente',
        '69' => 'Transação não permitida para este produto ou serviço',
        '70' => 'Parâmetro enviado com tamanho inválido',
        '71' => 'Formato do parâmetro inválido',
        '72' => 'Contate a central do cartão',
        '73' => 'Parâmetro obrigatório não está presente',
        '74' => 'Falha na comunicação, tente novamente',
        '75' => 'Parâmetro não deve ser enviado para este tipo de transação',
        '76' => 'Formato do parâmetro inválido',
        '78' => 'Transação não existe',
        '79' => 'Cartão vencido. Não tente novamente e contate a central do cartão',
        '80' => 'Saldo insuficiente. Contate a central do cartão',
        '82' => 'Transação não autorizada para cartão de débito',
        '83' => 'Não autorizado. Contate a central do cartão',
        '84' => 'Não autorizado. Não tente novamente e contate a central do cartão',
        '85' => 'Parâmetro enviado com tamanho inválido',
        '86' => 'Cartão vencido',
        '87' => 'Campo tid ou reference não está preenchido.',
        '88' => 'Lojista não aprovado. Regularize seu site e contate a Rede para voltar a transacionar.',
        '89' => 'Chave de integração inválida',
        '97' => 'Parâmetro enviado com tamanho inválido',
        '98' => 'Formato do parâmetro inválido',
        '99' => 'Formato do parâmetro inválido.',
        '100' => 'Formato do parâmetro inválido.',
        '101' => 'Problemas no cartão, contate a central do cartão',
        '102' => 'Confirme a situação da loja com a central do cartão',
        '103' => 'Não autorizado. Por favor, tente novamente.',
        '104' => 'Não autorizado. Por favor, tente novamente.',
        '105' => 'Cartão restrito',
        '106' => 'Erro no processamento. Tente novamente',
        '107' => 'Por favor, tente novamente.',
        '108' => 'Valor não permitido para este tipo de cartão.',
        '109' => 'Cartão inexistente',
        '110' => 'Tipo de transação não permitida para este cartão',
        '111' => 'Saldo insuficiente',
        '112' => 'Cartão expirado.',
        '113' => 'Emissor identificou risco moderado',
        '114' => 'O cartão não pertence a rede de pagamento',
        '115' => 'Limite de transações permitidas no período foi excedido.',
        '116' => 'Por favor, contate a central do cartão.',
        '117' => 'Transação não encontrada.',
        '118' => 'Cartão bloqueado.',
        '119' => 'Código de segurança inválido.',
        '121' => 'Erro no processamento. Por favor, tente novamente.',
        '122' => 'Transação enviada previamente.',
        '123' => 'Portador solicitou encerramento da recorrência na central do cartão.',
        '124' => 'Não autorizado. Contate a Rede.',
        '132' => 'Parâmetro enviado com tamanho inválido',
        '133' => 'Valor do parâmetro inválido',
        '150' => 'Tempo esgotado. Tente novamente',
        '151' => 'Valor do parâmetro maior do que o permitido',
        '153' => 'Valor do parâmetro inválido',
        '154' => 'Formato do parâmetro inválido',
        '155' => 'Parâmetro obrigatório não está presente',
        '156' => 'Parâmetro enviado com tamanho inválido',
        '157' => 'Parâmetro obrigatório não está presente',
        '158' => 'Valor não permitido para esta transação',
        '159' => 'Parâmetro enviado com tamanho inválido',
        '160' => 'Parâmetro obrigatório não está presente',
        '161' => 'Formato do parâmetro inválido',
        '167' => 'Pedido JSON inválido',
        '169' => 'Content-Type inválido',
        '170' => 'Transação Zero Dollar não permitida para este cartão.',
        '171' => 'Operação não permitida para essa transação',
        '172' => 'CVC2 exigido para transação Zero Dollar.',
        '173' => 'Autorização expirou',
        '174' => 'Transação Zero Dollar aprovada.',
        '175' => 'Transação Zero Dollar negada.',
        '176' => 'Parâmetro obrigatório não está presente',
        '200' => 'Autenticação realizada com sucesso',
        '201' => 'Autenticação não exigida.',
        '203' => 'Serviço não habilitado. Por favor, contate a Rede',
        '202' => 'Portador não autenticado.',
        '204' => 'Portador não registrado no programa de autenticação da central do cartão',
        '220' => 'Pedido de transação com autenticação recebida. URL de redirecionamento enviada.',
        '250' => 'Parâmetro obrigatório não está presente.',
        '251' => 'Formato do parâmetro inválido',
        '252' => 'Parâmetro obrigatório não está presente.',
        '253' => 'Parâmetro enviado com tamanho inválido',
        '254' => 'Formato do parâmetro inválido',
        '255' => 'Parâmetro obrigatório não está presente.',
        '256' => 'Parâmetro enviado com tamanho inválido',
        '257' => 'Formato do parâmetro inválido',
        '258' => 'Parâmetro obrigatório não está presente.',
        '259' => 'Parâmetro obrigatório não está presente.',
        '260' => 'Parâmetro obrigatório não está presente.',
        '261' => 'Parâmetro obrigatório não está presente.',
        '269' => 'ChallengePreference: Formato do parâmetro inválido',
        '351' => 'Cancelamento não permitido',
        '353' => 'Transação não encontrada',
        '354' => 'Período de estorno expirado',
        '355' => 'Transação já cancelada',
        '357' => 'Soma dos valores de estorno supera o valor da transação',
        '358' => 'Soma dos valores de estorno supera o valor processado disponível para estorno',
        '359' => 'Estorno realizado com sucesso.',
        '360' => 'Pedido de estorno realizado com sucesso.',
        '362' => 'Estorno não encontrado',
        '363' => 'Limite de caracteres da URL de Callback foi excedido',
        '365' => 'Estorno parcial não disponível',
        '368' => 'Sem sucesso. Por favor, tente novamente.',
        '369' => 'Estorno não encontrado',
        '370' => 'Pedido falhou. Contate a Rede',
        '371' => 'Transação não disponível para estorno. Tente novamente em algumas horas',
        '373' => 'Sem mais estornos permitidos',
        '374' => 'Estorno não permitido. Chargeback foi solicitado.',
        '898' => 'PV com ip de origem inválido',
        '899' => 'Sem sucesso. Por favor, contate a Rede',
        '1002' => 'Parâmetro enviado com tamanho inválido',
        '1003' => 'Parâmetro obrigatório não está presente.',
        '1018' => 'Parâmetro enviado com tamanho inválido',
        '1019' => 'Parâmetro obrigatório não está presente',
        '1020' => 'Formato do parâmetro inválido',
        '1021' => 'Parâmetro enviado com tamanho inválido',
        '1023' => 'Formato do parâmetro inválido',
        '1027' => 'Parâmetro enviado com tamanho inválido',
        '1030' => 'Parâmetro enviado com tamanho inválido',
        '1032' => 'Parâmetro enviado com tamanho inválido',
        '1034' => 'Parâmetro enviado com tamanho inválido',
        '1036' => 'Parâmetro enviado com tamanho inválido',
        '1038' => 'Parâmetro enviado com tamanho inválido',
        '3000' => 'ColorDepth: Parâmetro obrigatório não está presente',
        '3001' => 'DeviceType3ds: Parâmetro obrigatório não está presente',
        '3002' => 'JavaEnabled: Parâmetro obrigatório não está presente',
        '3003' => 'Language: Parâmetro obrigatório não está presente',
        '3004' => 'TimeZoneOffset: Parâmetro obrigatório não está presente',
        '3005' => 'ScreenHeight: Parâmetro obrigatório não está presente',
        '3006' => 'ScreenWidth: Parâmetro obrigatório não está presente',
        '3007' => 'ColorDepth: Tamanho do parâmetro inválido',
        '3008' => 'DeviceType3ds: Tamanho do parâmetro inválido',
        '3009' => 'Language: Tamanho do parâmetro inválido',
        '3010' => 'TimeZoneOffset: Tamanho do parâmetro inválido',
        '3011' => 'ScreenHeight: Tamanho do parâmetro inválido',
        '3012' => 'ScreenWidth: Formato do parâmetro inválido',
        '3013' => 'ColorDepth: Formato do parâmetro inválido',
        '3014' => 'DeviceType3ds: Formato do parâmetro inválido',
        '3015' => 'JavaEnabled: Formato do parâmetro inválido',
        '3016' => 'Language: Formato do parâmetro inválido',
        '3017' => 'TimeZoneOffset: Formato do parâmetro inválido',
        '3018' => 'ScreenHeight: Formato do parâmetro inválido',
        '3019' => 'ScreenWidth: Formato do parâmetro inválido',
        '3020' => 'Parâmetro enviado com tamanho inválido',
        '3025' => 'Negativa de categoria 01: Este cartão não deve ser usado novamente',
        '3026' => 'Negativa de categoria 02: Esse cartão não deve ser usado novamente nesse PV',
        '3027' => 'Negativa de categoria 03: Esse cartão não deve ser usado novamente nesse PV',
        '3028' => 'Parâmetro obrigatório não está presente',
        '3029' => 'Parâmetro enviado com tamanho inválido',
        '3030' => 'Formato do parâmetro inválido',
        '3031' => 'Parâmetro obrigatório não está presente',
        '3032' => 'Parâmetro enviado com tamanho inválido',
        '3033' => 'Parâmetro enviado com tamanho inválido',
        '3034' => 'Parâmetro enviado com tamanho inválido',
        '3035' => 'Formato do parâmetro inválido',
        '3036' => 'QrCode expirado.',
        '3052' => 'Parâmetro obrigatório não está presente',
        '3053' => 'Formato do parâmetro inválido',
        '3054' => 'Parâmetro enviado com tamanho inválido',
        '3055' => 'Parâmetro não permitido para esta transação',
        '3056' => 'Parâmetro não permitido para esta transação',
        '3064' => 'Parâmetro enviado com tamanho inválido',
        '3065' => 'Formato do parâmetro inválido.',
        '3066' => 'Parâmetro obrigatório não está presente.',
        '3067' => 'Parâmetro obrigatório não está presente.',
        '3068' => 'Parâmetro obrigatório não está presente.',
        '3069' => 'Formato do parâmetro inválido',
        '3070' => 'Parâmetro enviado com tamanho inválido',
        '3076' => 'QrCode: Campo Expiration Date não foi informado.',
        '3077' => 'QrCode: Campo Expiration Date enviado com valor inválido.',
        '3078' => 'QrCode: Campo Expiration Date enviado em formato inválido.',
        '3079' => 'QrCode não processado. Tente novamente.',
        '3081' => 'QrCode: Campo Expiration Date enviado em tamanho inválido.',
        '3084' => 'Erro na geração do campo qrCodeImage. Use a API de Consulta para obter essa informação, caso seja necessário.',
        '3085' => 'Erro na geração do campo qrCodeImage. Tente novamente.',
        '3089' => 'Qr Code não gerado, contate a Rede.',
        '3090' => 'Chave Pix Inválida na geração de qrCode.',
        '3091' => 'Erro na devolução, tente novamente.',
        '3092' => 'Falha na geração de qrCode, tente novamente.',
        '3094' => 'Sem sucesso. Contate a Rede.',
        '3095' => 'Chave Pix não cadastrada.',
        '3096' => 'Sem sucesso. Tente novamente mais tarde.',
        '3097' => 'Não disponível. Tente novamente mais tarde.',
        '3098' => 'Serviço não autorizado.',
        '3099' => 'Falha na comunicação. Tente novamente mais tarde.',
        '3100' => 'Formato do parâmetro inválido.',
        '3101' => 'Parâmetro enviado com tamanho inválido.',
        '3102' => 'Formato do parâmetro inválido.',
        '3103' => 'Parâmetro enviado com tamanho inválido',
        '3104' => 'Formato do parâmetro inválido.',
        '3105' => 'Formato do parâmetro inválido.',
        '3106' => 'Parâmetro enviado com tamanho inválido.',
        '3107' => 'Parâmetro obrigatório não está presente.',
        '3108' => 'Parâmetro obrigatório não está presente.',
        '3109' => 'Parâmetro obrigatório não está presente.',
        '3110' => 'Parâmetro obrigatório não está presente.',
        '3111' => 'Parâmetro obrigatório não está presente.',
        '3112' => 'Parâmetro não permitido para esta transação.',
        '3113' => 'Parâmetro enviado com tamanho inválido.',
        '3114' => 'Formato do parâmetro inválido.',
        '3115' => 'Parâmetro enviado com tamanho inválido.',
        '3116' => 'OFormato do parâmetro inválido.',
        '3117' => 'Parâmetro enviado com tamanho inválido.',
        '3118' => 'Formato do parâmetro inválido.',
        '3119' => 'Formato do parâmetro inválido',
        '3120' => 'Parâmetro enviado com tamanho inválido.',
        '3121' => 'Valor inválido.',
        '3122' => 'Valor inválido.',
        '3123' => 'O processo de devolução não foi concluído com sucesso. Por favor, repita a solicitação.',
        '3125' => 'Devolução negada por dados incorretos Revise os dados da transação e tente novamente.',
        '3128' => 'Devolução negada por bloqueio em conta junto a emissor, tente novamente.',
        '3130' => 'Formato do parâmetro inválido.',
        '3131' => 'Tamanho do parâmetro inválido.',
        '3132' => 'Tamanho do parâmetro inválido.',
        '3133' => 'Formato do parâmetro inválido.',
    ];

    const STATUS = [
        '00' => 'approved',
        '1' => 'failed',
        '2' => 'failed',
        '3' => 'failed',
        '4' => 'failed',
        '5' => 'failed',
        '6' => 'failed',
        '7' => 'failed',
        '8' => 'failed',
        '9' => 'failed',
        '10' => 'failed',
        '11' => 'failed',
        '12' => 'failed',
        '13' => 'failed',
        '14' => 'failed',
        '15' => 'failed',
        '16' => 'failed',
        '17' => 'failed',
        '18' => 'failed',
        '19' => 'failed',
        '20' => 'failed',
        '21' => 'failed',
        '22' => 'failed',
        '23' => 'failed',
        '24' => 'failed',
        '25' => 'failed',
        '26' => 'failed',
        '27' => 'failed',
        '28' => 'failed',
        '29' => 'failed',
        '30' => 'failed',
        '31' => 'failed',
        '32' => 'failed',
        '33' => 'failed',
        '34' => 'failed',
        '35' => 'failed',
        '36' => 'failed',
        '37' => 'failed',
        '38' => 'failed',
        '39' => 'failed',
        '40' => 'failed',
        '41' => 'failed',
        '42' => 'failed',
        '43' => 'failed',
        '44' => 'failed',
        '45' => 'failed',
        '46' => 'failed',
        '47' => 'failed',
        '48' => 'failed',
        '49' => 'failed',
        '50' => 'failed',
        '51' => 'failed',
        '53' => 'failed',
        '54' => 'failed',
        '55' => 'failed',
        '56' => 'failed',
        '57' => 'failed',
        '58' => 'failed',
        '59' => 'failed',
        '60' => 'failed',
        '61' => 'failed',
        '63' => 'failed',
        '64' => 'failed',
        '65' => 'failed',
        '66' => 'failed',
        '67' => 'failed',
        '68' => 'failed',
        '69' => 'failed',
        '70' => 'failed',
        '71' => 'failed',
        '72' => 'failed',
        '73' => 'failed',
        '74' => 'failed',
        '75' => 'failed',
        '76' => 'failed',
        '78' => 'failed',
        '79' => 'failed',
        '80' => 'failed',
        '82' => 'failed',
        '83' => 'failed',
        '84' => 'failed',
        '85' => 'failed',
        '86' => 'failed',
        '87' => 'failed',
        '88' => 'failed',
        '89' => 'failed',
        '97' => 'failed',
        '98' => 'failed',
        '99' => 'failed',
        '100' => 'failed',
        '101' => 'failed',
        '102' => 'failed',
        '103' => 'failed',
        '104' => 'failed',
        '105' => 'failed',
        '106' => 'failed',
        '107' => 'failed',
        '108' => 'failed',
        '109' => 'failed',
        '110' => 'failed',
        '111' => 'failed',
        '112' => 'failed',
        '113' => 'failed',
        '114' => 'failed',
        '115' => 'failed',
        '116' => 'failed',
        '117' => 'failed',
        '118' => 'failed',
        '119' => 'failed',
        '121' => 'failed',
        '122' => 'failed',
        '123' => 'failed',
        '124' => 'failed',
        '132' => 'failed',
        '133' => 'failed',
        '150' => 'failed',
        '151' => 'failed',
        '153' => 'failed',
        '154' => 'failed',
        '155' => 'failed',
        '156' => 'failed',
        '157' => 'failed',
        '158' => 'failed',
        '159' => 'failed',
        '160' => 'failed',
        '161' => 'failed',
        '167' => 'failed',
        '169' => 'failed',
        '170' => 'failed',
        '171' => 'failed',
        '172' => 'failed',
        '173' => 'failed',
        '174' => 'failed',
        '175' => 'failed',
        '176' => 'failed',
        '200' => 'failed',
        '201' => 'failed',
        '203' => 'failed',
        '202' => 'failed',
        '204' => 'failed',
        '220' => 'failed',
        '250' => 'failed',
        '251' => 'failed',
        '252' => 'failed',
        '253' => 'failed',
        '254' => 'failed',
        '255' => 'failed',
        '256' => 'failed',
        '257' => 'failed',
        '258' => 'failed',
        '259' => 'failed',
        '260' => 'failed',
        '261' => 'failed',
        '269' => 'failed',
        '351' => 'failed',
        '353' => 'failed',
        '354' => 'expired',
        '355' => 'cancelled',
        '357' => 'paid',
        '358' => 'paid',
        '359' => 'refunded',
        '360' => 'refund_pending',
        '362' => 'paid',
        '363' => 'paid',
        '365' => 'paid',
        '368' => 'failed',
        '369' => 'paid',
        '370' => 'failed',
        '371' => 'paid',
        '373' => 'paid',
        '374' => 'paid',
        '898' => 'failed',
        '899' => 'failed',
        '1002' => 'failed',
        '1003' => 'failed',
        '1018' => 'failed',
        '1019' => 'failed',
        '1020' => 'failed',
        '1021' => 'failed',
        '1023' => 'failed',
        '1027' => 'failed',
        '1030' => 'failed',
        '1032' => 'failed',
        '1034' => 'failed',
        '1036' => 'failed',
        '1038' => 'failed',
        '3000' => 'failed',
        '3001' => 'failed',
        '3002' => 'failed',
        '3003' => 'failed',
        '3004' => 'failed',
        '3005' => 'failed',
        '3006' => 'failed',
        '3007' => 'failed',
        '3008' => 'failed',
        '3009' => 'failed',
        '3010' => 'failed',
        '3011' => 'failed',
        '3012' => 'failed',
        '3013' => 'failed',
        '3014' => 'failed',
        '3015' => 'failed',
        '3016' => 'failed',
        '3017' => 'failed',
        '3018' => 'failed',
        '3019' => 'failed',
        '3020' => 'failed',
        '3025' => 'failed',
        '3026' => 'failed',
        '3027' => 'failed',
        '3028' => 'failed',
        '3029' => 'failed',
        '3030' => 'failed',
        '3031' => 'failed',
        '3032' => 'failed',
        '3033' => 'failed',
        '3034' => 'failed',
        '3035' => 'failed',
        '3036' => 'expired',
        '3052' => 'failed',
        '3053' => 'failed',
        '3054' => 'failed',
        '3055' => 'failed',
        '3056' => 'failed',
        '3064' => 'failed',
        '3065' => 'failed',
        '3066' => 'failed',
        '3067' => 'failed',
        '3068' => 'failed',
        '3069' => 'failed',
        '3070' => 'failed',
        '3076' => 'failed',
        '3077' => 'failed',
        '3078' => 'failed',
        '3079' => 'failed',
        '3081' => 'failed',
        '3084' => 'failed',
        '3085' => 'failed',
        '3089' => 'failed',
        '3090' => 'failed',
        '3091' => 'failed',
        '3092' => 'failed',
        '3094' => 'failed',
        '3095' => 'failed',
        '3096' => 'failed',
        '3097' => 'failed',
        '3098' => 'failed',
        '3099' => 'failed',
        '3100' => 'failed',
        '3101' => 'failed',
        '3102' => 'failed',
        '3103' => 'failed',
        '3104' => 'failed',
        '3105' => 'failed',
        '3106' => 'failed',
        '3107' => 'failed',
        '3108' => 'failed',
        '3109' => 'failed',
        '3110' => 'failed',
        '3111' => 'failed',
        '3112' => 'failed',
        '3113' => 'failed',
        '3114' => 'failed',
        '3115' => 'failed',
        '3116' => 'failed',
        '3117' => 'failed',
        '3118' => 'failed',
        '3119' => 'failed',
        '3120' => 'failed',
        '3121' => 'failed',
        '3122' => 'failed',
        '3123' => 'failed',
        '3125' => 'failed',
        '3128' => 'failed',
        '3130' => 'failed',
        '3131' => 'failed',
        '3132' => 'failed',
        '3133' => 'failed',
    ];

    public static function existsReturnCode(?string $code = null): bool
    {
        return in_array(needle: $code, haystack: ReturnResponse::CODES, strict: true);
    }

    public static function getReturnMessage(?string $code = null): string
    {
        return ReturnResponse::existsReturnCode(code: $code) ? ReturnResponse::MESSAGES[$code] : 'Erro no processamento (Erro não mapeado). Tente novamente';
    }
}
